import { Template } from '../types/template';
import { createDynamicRenderer } from '../utils/dynamicRenderer';

// 1. Folha A4 Pimaco 30 Etiquetas (3 colunas x 10 linhas)
const pimaco30Def = {
  id: 'pimaco-a4-30',
  name: 'Folha Pimaco A4 (30 Etiquetas)',
  category: 'a4-sheet' as const,
  description: 'Padrão Pimaco 66.7 × 25.4 mm (3x10). Ideal para produtos, preços e códigos de barras.',
  dimensions: {
    widthMm: 210,
    heightMm: 297,
    orientation: 'portrait' as const,
  },
  grid: {
    rows: 10,
    cols: 3,
    marginTopMm: 21.2,
    marginLeftMm: 4.8,
    gapX: 2.5,
    gapY: 0,
    labelWidthMm: 66.7,
    labelHeightMm: 25.4,
  },
  fields: [
    {
      key: 'produto',
      label: 'Nome do Produto / Título',
      type: 'text' as const,
      defaultValue: 'PRODUTO PREMIUM BR',
      required: true,
      xMm: 2,
      yMm: 2,
      widthMm: 62.7,
      heightMm: 5,
      fontSizePt: 8,
      fontWeight: 'bold' as const,
      textAlign: 'center' as const,
    },
    {
      key: 'codigo',
      label: 'Código EAN-13 / Barra',
      type: 'barcode' as const,
      barcodeFormat: 'CODE128' as const,
      defaultValue: '789123456789',
      required: true,
      xMm: 3,
      yMm: 7.5,
      widthMm: 40,
      heightMm: 12,
      fontSizePt: 6.5,
    },
    {
      key: 'preco',
      label: 'Preço (R$)',
      type: 'text' as const,
      defaultValue: 'R$ 29,90',
      required: true,
      xMm: 44,
      yMm: 8.5,
      widthMm: 20,
      heightMm: 10,
      fontSizePt: 10,
      fontWeight: 'bolder' as const,
      textAlign: 'center' as const,
    },
  ],
};

// 2. Cartões de Visita A4 (Grade 2 x 5 - 10 cartões por folha)
const cartoesVisitaDef = {
  id: 'cartoes-visita-a4-10',
  name: 'Cartões de Visita A4 (10 Cartões 90×50mm)',
  category: 'a4-sheet' as const,
  description: 'Folha A4 com 10 cartões de 90×50 mm com suporte a marcas de corte entre cartões.',
  dimensions: {
    widthMm: 210,
    heightMm: 297,
    orientation: 'portrait' as const,
  },
  grid: {
    rows: 5,
    cols: 2,
    marginTopMm: 23.5,
    marginLeftMm: 15,
    gapX: 0,
    gapY: 0,
    labelWidthMm: 90,
    labelHeightMm: 50,
  },
  fields: [
    {
      key: 'empresa',
      label: 'Empresa / Marca',
      type: 'text' as const,
      defaultValue: 'STUDIO DESIGN & PRINT',
      required: true,
      xMm: 5,
      yMm: 5,
      widthMm: 80,
      heightMm: 6,
      fontSizePt: 10,
      fontWeight: 'bold' as const,
      textAlign: 'left' as const,
    },
    {
      key: 'nome',
      label: 'Nome Profissional',
      type: 'text' as const,
      defaultValue: 'Carlos E. Silveira',
      required: true,
      xMm: 5,
      yMm: 14,
      widthMm: 55,
      heightMm: 6,
      fontSizePt: 11,
      fontWeight: 'bolder' as const,
      textAlign: 'left' as const,
    },
    {
      key: 'cargo',
      label: 'Cargo / Especialidade',
      type: 'text' as const,
      defaultValue: 'Diretor de Produção Gráfica',
      required: false,
      xMm: 5,
      yMm: 20,
      widthMm: 55,
      heightMm: 5,
      fontSizePt: 7.5,
      textAlign: 'left' as const,
    },
    {
      key: 'contato',
      label: 'Telefone / WhatsApp',
      type: 'text' as const,
      defaultValue: '(11) 98765-4321',
      required: true,
      xMm: 5,
      yMm: 28,
      widthMm: 55,
      heightMm: 5,
      fontSizePt: 8,
      fontWeight: 'bold' as const,
      textAlign: 'left' as const,
    },
    {
      key: 'email',
      label: 'E-mail / Site',
      type: 'text' as const,
      defaultValue: 'contato@studiodesign.com.br',
      required: false,
      xMm: 5,
      yMm: 34,
      widthMm: 55,
      heightMm: 5,
      fontSizePt: 7.5,
      textAlign: 'left' as const,
    },
    {
      key: 'qrcode',
      label: 'QR Code (PIX ou Link)',
      type: 'qrcode' as const,
      defaultValue: 'https://studiodesign.com.br',
      required: false,
      xMm: 64,
      yMm: 16,
      widthMm: 22,
      heightMm: 22,
    },
  ],
};

// 3. Etiqueta Térmica de Envio 100x150 mm (Mercado Livre / Correios / ZPL)
const etiquetaEnvioDef = {
  id: 'etiqueta-termica-envio',
  name: 'Etiqueta Térmica de Envio (100×150 mm)',
  category: 'thermal' as const,
  description: 'Padrão logístico para impressoras térmicas (Zebra, Elgin, Argox) para e-commerce.',
  dimensions: {
    widthMm: 100,
    heightMm: 150,
    orientation: 'portrait' as const,
  },
  fields: [
    {
      key: 'transportadora',
      label: 'Canal de Envio',
      type: 'text' as const,
      defaultValue: 'MERCADO ENVIOS / PAC CORREIOS',
      required: true,
      xMm: 4,
      yMm: 4,
      widthMm: 92,
      heightMm: 7,
      fontSizePt: 10,
      fontWeight: 'bolder' as const,
      textAlign: 'center' as const,
      showBorder: true,
    },
    {
      key: 'rastreio',
      label: 'Código de Rastreio',
      type: 'barcode' as const,
      barcodeFormat: 'CODE128' as const,
      defaultValue: 'BR98765432101',
      required: true,
      xMm: 6,
      yMm: 14,
      widthMm: 88,
      heightMm: 24,
      fontSizePt: 9,
    },
    {
      key: 'destinatario',
      label: 'Destinatário',
      type: 'text' as const,
      defaultValue: 'Ana Clara Albuquerque\nAv. Paulista, 1578, Apto 82\nBela Vista - São Paulo / SP',
      required: true,
      xMm: 4,
      yMm: 43,
      widthMm: 92,
      heightMm: 22,
      fontSizePt: 9,
      fontWeight: 'bold' as const,
      showBorder: true,
    },
    {
      key: 'cep',
      label: 'CEP',
      type: 'text' as const,
      defaultValue: 'CEP: 01310-200',
      required: true,
      xMm: 4,
      yMm: 68,
      widthMm: 50,
      heightMm: 8,
      fontSizePt: 12,
      fontWeight: 'bolder' as const,
    },
    {
      key: 'qrcode',
      label: 'QR Code de Triagem',
      type: 'qrcode' as const,
      defaultValue: 'BR98765432101-01310200',
      required: true,
      xMm: 66,
      yMm: 68,
      widthMm: 28,
      heightMm: 28,
    },
    {
      key: 'remetente',
      label: 'Remetente',
      type: 'text' as const,
      defaultValue: 'Remetente: Central Gráfica Express\nDoc: 12.345.678/0001-90\nNF-e: 004.891',
      required: false,
      xMm: 4,
      yMm: 102,
      widthMm: 92,
      heightMm: 20,
      fontSizePt: 7.5,
      showBorder: true,
    },
  ],
};

// 4. Etiqueta Gôndola / Varejo (60 x 40 mm)
const gondolaDef = {
  id: 'etiqueta-gondola-60x40',
  name: 'Etiqueta Gôndola / Varejo (60×40 mm)',
  category: 'thermal' as const,
  description: 'Etiqueta rápida de preço e gôndola para impressoras de bobina térmica ou rolo adesivo.',
  dimensions: {
    widthMm: 60,
    heightMm: 40,
    orientation: 'landscape' as const,
  },
  fields: [
    {
      key: 'descricao',
      label: 'Descrição do Item',
      type: 'text' as const,
      defaultValue: 'CAFÉ TORRADO EM GRÃOS 500G',
      required: true,
      xMm: 2,
      yMm: 2,
      widthMm: 56,
      heightMm: 7,
      fontSizePt: 8,
      fontWeight: 'bolder' as const,
      textAlign: 'center' as const,
    },
    {
      key: 'codigo',
      label: 'Código de Barras',
      type: 'barcode' as const,
      barcodeFormat: 'CODE128' as const,
      defaultValue: '789876543210',
      required: true,
      xMm: 2,
      yMm: 10,
      widthMm: 34,
      heightMm: 18,
      fontSizePt: 7,
    },
    {
      key: 'preco',
      label: 'Preço Varejo',
      type: 'text' as const,
      defaultValue: 'R$ 34,90',
      required: true,
      xMm: 37,
      yMm: 11,
      widthMm: 21,
      heightMm: 14,
      fontSizePt: 12,
      fontWeight: 'bolder' as const,
      textAlign: 'center' as const,
    },
    {
      key: 'unidade',
      label: 'Info Adicional',
      type: 'text' as const,
      defaultValue: 'Preço por kg: R$ 69,80 | Val: 12/2026',
      required: false,
      xMm: 2,
      yMm: 30,
      widthMm: 56,
      heightMm: 6,
      fontSizePt: 6.5,
      textAlign: 'center' as const,
    },
  ],
};

// 5. Cartaz Promocional A3 (297 x 420 mm)
const cartazA3Def = {
  id: 'cartaz-promocional-a3',
  name: 'Cartaz Promocional A3 (297×420 mm)',
  category: 'document' as const,
  description: 'Cartaz publicitário tamanho A3 para vitrines, promoções e sinalização interna.',
  dimensions: {
    widthMm: 297,
    heightMm: 420,
    orientation: 'portrait' as const,
  },
  fields: [
    {
      key: 'destaque',
      label: 'Destaque Superior',
      type: 'text' as const,
      defaultValue: 'SUPER OFERTA DA SEMANA',
      required: true,
      xMm: 15,
      yMm: 20,
      widthMm: 267,
      heightMm: 20,
      fontSizePt: 22,
      fontWeight: 'bolder' as const,
      textAlign: 'center' as const,
    },
    {
      key: 'titulo',
      label: 'Nome do Produto / Evento',
      type: 'text' as const,
      defaultValue: 'IMPRESSÃO DIGITAL DE ALTA RESOLUÇÃO',
      required: true,
      xMm: 15,
      yMm: 50,
      widthMm: 267,
      heightMm: 35,
      fontSizePt: 26,
      fontWeight: 'bolder' as const,
      textAlign: 'center' as const,
    },
    {
      key: 'preco',
      label: 'Preço / Chamada Promocional',
      type: 'text' as const,
      defaultValue: 'A PARTIR DE R$ 1,99',
      required: true,
      xMm: 25,
      yMm: 120,
      widthMm: 247,
      heightMm: 45,
      fontSizePt: 36,
      fontWeight: 'bolder' as const,
      textAlign: 'center' as const,
      showBorder: true,
    },
    {
      key: 'condicoes',
      label: 'Condições de Pagamento',
      type: 'text' as const,
      defaultValue: 'TIRAGEM MÍNIMA 100 UNIDADES • PARCELAMENTO EM ATÉ 6X SEM JUROS',
      required: false,
      xMm: 15,
      yMm: 180,
      widthMm: 267,
      heightMm: 15,
      fontSizePt: 12,
      fontWeight: 'bold' as const,
      textAlign: 'center' as const,
    },
    {
      key: 'qrcode',
      label: 'QR Code de Contato / Pedido',
      type: 'qrcode' as const,
      defaultValue: 'https://wa.me/5511999999999?text=Quero%20fazer%20um%20pedido',
      required: false,
      xMm: 118,
      yMm: 220,
      widthMm: 60,
      heightMm: 60,
    },
    {
      key: 'rodape',
      label: 'Texto do Rodapé / Validade',
      type: 'text' as const,
      defaultValue: 'Folium Print • Imprima com precisão milimétrica • Promoção válida até durar o estoque.',
      required: false,
      xMm: 15,
      yMm: 380,
      widthMm: 267,
      heightMm: 10,
      fontSizePt: 10,
      textAlign: 'center' as const,
    },
  ],
};

export const BUILTIN_TEMPLATES: Template[] = [
  {
    ...pimaco30Def,
    render: createDynamicRenderer(pimaco30Def),
  },
  {
    ...cartoesVisitaDef,
    render: createDynamicRenderer(cartoesVisitaDef),
  },
  {
    ...etiquetaEnvioDef,
    render: createDynamicRenderer(etiquetaEnvioDef),
  },
  {
    ...gondolaDef,
    render: createDynamicRenderer(gondolaDef),
  },
  {
    ...cartazA3Def,
    render: createDynamicRenderer(cartazA3Def),
  },
];
